### ISSUE TITLE
Could you upload your faster rcnn code to extract region features for my own data?

### ISSUE THREAD

**Issue by AcodeC** [tgc1997/RMN#2]

**Comment by daqingliu** [comment]
We extracted region features by [bottom-up-attention](https://github.com/peteanderson80/bottom-up-attention).

**Comment by AcodeC** [comment]
> We extracted region features by [bottom-up-attention](https://github.com/peteanderson80/bottom-up-attention).

Could you share the bottom-up-attention code which you have changed for extract MSVD or MSRVTT dataset?  Thank you very much! Your work is awesome!

**Comment by tgc1997** [comment]
> Could you share the bottom-up-attention code which you have changed for extract MSVD or MSRVTT dataset? Thank you very much! Your work is awesome!

Our feature extracting code is stored in the server of our lab, but unfortunately, someone reinstalled the system without informing us so that the code was deleted. We extracted video region features based on  [extract_feature.py](https://github.com/daqingliu/bottom-up-attention/blob/master/tools/extract_feature.py). This repo made some changes to the original repo and is easier to use,  you could easily extract one image's region features by this code. As for MSVD and MSR-VTT, you can first convert a video to frames, and then extract features for the frames you want.

**Comment by AcodeC** [comment]
> > Could you share the bottom-up-attention code which you have changed for extract MSVD or MSRVTT dataset? Thank you very much! Your work is awesome!
> 
> Our feature extracting code is stored in the server of our lab, but unfortunately, someone reinstalled the system without informing us so that the code was deleted. We extracted video region features based on [extract_feature.py](https://github.com/daqingliu/bottom-up-attention/blob/master/tools/extract_feature.py). This repo made some changes to the original repo and is easier to use, you could easily extract one image's region features by this code. As for MSVD and MSR-VTT, you can first convert a video to frames, and then extract features for the frames you want.

That's a pity. And thank you very much!
